name: 'Link Check'

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '34 12 * * *'

jobs:
  link-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: run muffet filer
        run: ./.muffet-filter/muffet-filter -i ./.muffet-filter/ignores.json https://bhamail.github.io/picapsule/
